Update cmake-multi-platform.yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -73,3 +73,27 @@ jobs:
       # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest --build-config ${{ matrix.build_type }}
+
+    - name: Run Executable
+      shell: bash
+      working-directory: ${{ steps.strings.outputs.build-output-dir }}
+      run: |
+        echo "Running benchmark tests..."
+        executable_name="main"
+  
+        if [[ "$RUNNER_OS" == "Windows" ]]; then
+          executable_name="main.exe"
+          executable_path="Release/$executable_name"  # Windows binary is in Release/
+        else
+          executable_path="./$executable_name"  # Linux/macOS binary
+        fi
+  
+          # Check if the executable exists before running
+        echo "Checking if executable exists: $executable_path"
+        if [ -f "$executable_path" ]; then
+          echo "Executable found, running it..."
+          "$executable_path"
+        else
+          echo "Error: Executable not found at $executable_path"
+          exit 1
+        fi
